### PR TITLE
Clean code and add a TODO for improve the project set with Good Practice

### PR DESCRIPTION
**Pull request by feyroozecode**
a first pull request of sample dart code with deletation of windows and linux platforms

### CODE REVIEW

**Comment by feyroozecode** [comment]
i gonna to add some update for learn and funs In Sha'a Allah and for help other new developer to learn good practice and clean code and improve the animations . thanks

**Comment by omarfarouk228** [comment]
Hello Ibrahim,
Don't hesitate to add new features. It's my pleasure.

Best regards,
*Omar Farouk KOUGBADA*
*Ingénieur Logiciel Sénior Full Stack, Formateur et Consultant Informatique*
*+22893554740**/+22870441636**/+22899179270*
*https://www.ofaroukk.com* <https://www.ofaroukk.com>

**Comment by feyroozecode** [comment]
Thank you Omar

**Review by feyroozecode — COMMENTED** [review]
All is fine , check ✅ all refactor ming @ramofarouk

**Pull request merged**
